package inc::PotraceMakeMaker;
use Moose;

extends 'Dist::Zilla::Plugin::MakeMaker::Awesome';

override _build_WriteMakefile_args => sub {
   return {
      %{super()},
      INC => '',
      LIBS => ['-lpotrace'],
      CONFIGURE_REQUIRES => {
         'Devel::CheckLib' => '1.01',
      },
      META_MERGE => {
         'meta-spec' => { version => 2 },
         resources => {
            repository => {
               type => 'git',
               url  => 'https://github.com/polettix/Graphics-Potrace.git',
               web  => 'https://github.com/polettix/Graphics-Potrace',
            },
         },
      },
   };
};

override _build_MakeFile_PL_template => sub {
    my $template = <<'TEMPLATE';
# This Makefile.PL for {{ $distname }} was generated by Dist::Zilla.
# Don't edit it but the dist.ini used to construct it.
{{ $perl_prereq ? qq[BEGIN { require $perl_prereq; }] : ''; }}
use strict;
use warnings;
use ExtUtils::MakeMaker {{ $eumm_version }};
{{ $share_dir_block[0] }}

use Devel::CheckLib;
check_lib_or_exit( lib => 'potrace', header => 'potracelib.h' );

my {{ $WriteMakefileArgs }}

unless ( eval { ExtUtils::MakeMaker->VERSION(6.56) } ) {
  my $br = delete $WriteMakefileArgs{BUILD_REQUIRES};
  my $pp = $WriteMakefileArgs{PREREQ_PM};
  for my $mod ( keys %$br ) {
    if ( exists $pp->{$mod} ) {
      $pp->{$mod} = $br->{$mod} if $br->{$mod} > $pp->{$mod};
    }
    else {
      $pp->{$mod} = $br->{$mod};
    }
  }
}

delete $WriteMakefileArgs{CONFIGURE_REQUIRES}
  unless eval { ExtUtils::MakeMaker->VERSION(6.52) };

WriteMakefile(%WriteMakefileArgs);
{{ $share_dir_block[1] }}
TEMPLATE

  return $template;
};

__PACKAGE__->meta->make_immutable();

1;
